unit UDM;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ZSqlUpdate, DB, ZAbstractRODataset, ZAbstractDataset, ZDataset,
  ZConnection, IniFiles;

type
  TDM = class(TForm)
    DB: TZConnection;
    QEstado: TZQuery;
    DSEstado: TDataSource;
    UpdateEstado: TZUpdateSQL;
    QCidade: TZQuery;
    DSCidade: TDataSource;
    UpdateCidade: TZUpdateSQL;
    QCliente: TZQuery;
    DSCliente: TDataSource;
    UpdateCliente: TZUpdateSQL;
    QFornecedor: TZQuery;
    DSFornecedor: TDataSource;
    UpdateFornecedor: TZUpdateSQL;
    QMarca: TZQuery;
    DSMarca: TDataSource;
    UpdateMarca: TZUpdateSQL;
    QCategoria: TZQuery;
    DSCategoria: TDataSource;
    UpdateCategoria: TZUpdateSQL;
    QFormaPagamento: TZQuery;
    DSFormaPagamento: TDataSource;
    UpdateFormaPagamento: TZUpdateSQL;
    QCondicaoPagamento: TZQuery;
    DSCondicaoPagamento: TDataSource;
    UpdateCondicaoPagamento: TZUpdateSQL;
    QParcelas: TZQuery;
    DSParcelas: TDataSource;
    UpdateParcelas: TZUpdateSQL;
    QProduto: TZQuery;
    DSProduto: TDataSource;
    UpdateProduto: TZUpdateSQL;
    QVenda: TZQuery;
    DSVenda: TDataSource;
    UpdateVenda: TZUpdateSQL;
    QProdutoVenda: TZQuery;
    DSProdutoVenda: TDataSource;
    UpdateProdutoVenda: TZUpdateSQL;
    QCargo: TZQuery;
    DSCargo: TDataSource;
    UpdateCargo: TZUpdateSQL;
    QFuncionario: TZQuery;
    DSFuncionario: TDataSource;
    UpdateFuncionario: TZUpdateSQL;
    QPais: TZQuery;
    DSPais: TDataSource;
    UpdatePais: TZUpdateSQL;
    QContasReceber: TZQuery;
    DSContasReceber: TDataSource;
    UpdateContasReceber: TZUpdateSQL;
    QUsuario: TZQuery;
    DSUsuario: TDataSource;
    UpdateUsuario: TZUpdateSQL;
    QProdutoCompra: TZQuery;
    DSProdutoCompra: TDataSource;
    UpdateProdutoCompra: TZUpdateSQL;
    QCompra: TZQuery;
    DSCompra: TDataSource;
    UpdateCompra: TZUpdateSQL;
    QContasPagar: TZQuery;
    DSContasPagar: TDataSource;
    UpdateContasPagar: TZUpdateSQL;
    QEstadoidestado: TIntegerField;
    QEstadoidpais: TIntegerField;
    QEstadodescricao: TWideStringField;
    QEstadouf: TWideStringField;
    QEstadodatacadastro: TDateField;
    QEstadodataalteracao: TDateField;
    QCidadeidcidade: TIntegerField;
    QCidadeidestado: TIntegerField;
    QCidadedescricao: TWideStringField;
    QCidadeddd: TWideStringField;
    QCidadedatacadastro: TDateField;
    QCidadedataalteracao: TDateField;
    QMarcaidmarca: TIntegerField;
    QMarcadescricao: TWideStringField;
    QMarcadatacadastro: TDateField;
    QMarcadataalteracao: TDateField;
    QCategoriaidcategoria: TIntegerField;
    QCategoriadescricao: TWideStringField;
    QCategoriadatacadastro: TDateField;
    QCategoriadataalteracao: TDateField;
    QClienteidcliente: TIntegerField;
    QClientenome_razaosocial: TWideStringField;
    QClientelogradouro: TWideStringField;
    QClientenumero: TWideStringField;
    QClientecep: TWideStringField;
    QClientebairro: TWideStringField;
    QClientecomplemento: TWideStringField;
    QClienteidcidade: TIntegerField;
    QClienteemail: TWideStringField;
    QClientetelefone: TWideStringField;
    QClientecelular: TWideStringField;
    QClientecpf_cnpj: TWideStringField;
    QClienterg_ie: TWideStringField;
    QClientetipopessoa: TWideStringField;
    QClienteidcondicaopagamento: TIntegerField;
    QClientedatanasc_fund: TDateField;
    QClientedatacadastro: TDateField;
    QClientedataalteracao: TDateField;
    QClienteobservacao: TWideStringField;
    QFuncionarioidfuncionario: TIntegerField;
    QFuncionarionome: TWideStringField;
    QFuncionarioidcargo: TIntegerField;
    QFuncionariologradouro: TWideStringField;
    QFuncionarionumero: TWideStringField;
    QFuncionariocep: TWideStringField;
    QFuncionariobairro: TWideStringField;
    QFuncionariocomplemento: TWideStringField;
    QFuncionarioidcidade: TIntegerField;
    QFuncionarioemail: TWideStringField;
    QFuncionariotelefone: TWideStringField;
    QFuncionariocelular: TWideStringField;
    QFuncionariocpf: TWideStringField;
    QFuncionariorg: TWideStringField;
    QFuncionariodatanascimento: TDateField;
    QFuncionarioctps: TWideStringField;
    QFuncionariocnh: TWideStringField;
    QFuncionariodatavencimento: TDateField;
    QFuncionariodatacadastro: TDateField;
    QFuncionariodataalteracao: TDateField;
    QFuncionariodataadmissao: TDateField;
    QFuncionariodatademissao: TDateField;
    QFuncionarioobservacao: TWideStringField;
    QCargoidcargo: TIntegerField;
    QCargodescricao: TWideStringField;
    QCargodatacadastro: TDateField;
    QCargodataalteracao: TDateField;
    QUsuarioidusuario: TIntegerField;
    QUsuariologin: TWideStringField;
    QUsuariosenha: TWideStringField;
    QUsuarioidfuncionario: TIntegerField;
    QUsuariostatus: TWideStringField;
    QUsuariodatacadastro: TDateField;
    QUsuariodataalteracao: TDateField;
    QCondicaoPagamentoidcondicaopagamento: TIntegerField;
    QCondicaoPagamentoidformapagamento: TIntegerField;
    QCondicaoPagamentodescricao: TWideStringField;
    QCondicaoPagamentodatacadastro: TDateField;
    QCondicaoPagamentodataalteracao: TDateField;
    QFormaPagamentoidformapagamento: TIntegerField;
    QFormaPagamentodescricao: TWideStringField;
    QFormaPagamentodatacadastro: TDateField;
    QFormaPagamentodataalteracao: TDateField;
    QParcelasidcondicaopagamento: TIntegerField;
    QParcelasnumparcela: TIntegerField;
    QParcelasnumdias: TIntegerField;
    QParcelasporcentagem: TFloatField;
    QUnidade: TZQuery;
    DSUnidade: TDataSource;
    UpdateUnidade: TZUpdateSQL;
    QUnidadeidunidade: TIntegerField;
    QUnidadedescricao: TWideStringField;
    QUnidadedatacadastro: TDateField;
    QUnidadedataalteracao: TDateField;
    QVendanumnota: TIntegerField;
    QVendaserienota: TWideStringField;
    QVendaidcliente: TIntegerField;
    QVendaidcondicaopagamento: TIntegerField;
    QVendaidusuario: TIntegerField;
    QVendastatus: TWideStringField;
    QVendadatavenda: TDateField;
    QVendadataemissao: TDateField;
    QVendadatacadastro: TDateField;
    QVendadataalteracao: TDateField;
    QVendaobservacao: TWideStringField;
    QContasRecebernumnota: TIntegerField;
    QContasReceberserienota: TWideStringField;
    QContasRecebernumparcela: TIntegerField;
    QContasReceberidcliente: TIntegerField;
    QContasReceberidformapagamento: TIntegerField;
    QContasReceberidusuario: TIntegerField;
    QContasReceberdataemissao: TDateField;
    QContasReceberdatavencimento: TDateField;
    QContasReceberdatapagamento: TDateField;
    QContasRecebervalor: TFloatField;
    QContasReceberjuros: TFloatField;
    QContasRecebermulta: TFloatField;
    QContasReceberdesconto: TFloatField;
    QContasReceberstatus: TWideStringField;
    QContasReceberdatacadastro: TDateField;
    QContasReceberdataalteracao: TDateField;
    QContasReceberobservacao: TWideStringField;
    QProdutoVendaidproduto_venda: TIntegerField;
    QProdutoVendanumnota: TIntegerField;
    QProdutoVendaidproduto: TIntegerField;
    QProdutoVendaserienota: TWideStringField;
    QProdutoVendavalorunitario: TFloatField;
    QProdutoVendaquantidade: TFloatField;
    QProdutoVendadesconto: TFloatField;
    QProdutoFornecedor: TZQuery;
    DSProdutoFornecedor: TDataSource;
    UpdateProdutoFornecedor: TZUpdateSQL;
    QProdutoFornecedoridfornecedor: TIntegerField;
    QProdutoFornecedoridproduto: TIntegerField;
    QProdutoCompranumnota: TIntegerField;
    QProdutoCompraserienota: TWideStringField;
    QProdutoCompraidfornecedor: TIntegerField;
    QProdutoCompraidproduto: TIntegerField;
    QProdutoCompraidcompra: TIntegerField;
    QProdutoCompraunidade: TWideStringField;
    QProdutoCompraquantidade: TFloatField;
    QProdutoCompraprecocusto: TFloatField;
    QProdutoCompradesconto: TFloatField;
    QProdutoCompravalortotal: TFloatField;
    QProdutoComprabaseicms: TFloatField;
    QProdutoCompravaloricms: TFloatField;
    QProdutoCompravaloripi: TFloatField;
    QProdutoCompraicms: TFloatField;
    QProdutoCompraipi: TFloatField;
    QEstadopaís: TStringField;
    QCidadeestado: TStringField;
    QContasRecebercliente: TStringField;
    QContasReceberformapagamento: TStringField;
    QCompraidcompra: TIntegerField;
    QCompranumnota: TIntegerField;
    QCompraserienota: TWideStringField;
    QCompraidfornecedor: TIntegerField;
    QCompraidcondicaopagamento: TIntegerField;
    QCompraidusuario: TIntegerField;
    QCompraidtransportadora: TIntegerField;
    QCompratipofrete: TIntegerField;
    QComprabase_icms: TFloatField;
    QCompravalor_frete: TFloatField;
    QCompratotal_icms: TFloatField;
    QCompratotal_ipi: TFloatField;
    QCompravalor_desconto: TFloatField;
    QCompratotal_produto: TFloatField;
    QCompratotal_nota: TFloatField;
    QComprastatus: TWideStringField;
    QCompradatacompra: TDateField;
    QCompradataemissao: TDateField;
    QCompradatacadastro: TDateField;
    QCompradataalteracao: TDateField;
    QCompraobservacao: TWideStringField;
    QCompracondiçãoPgto: TStringField;
    QComprafornecedor: TStringField;
    QProdutoComprancm_sh: TWideStringField;
    QVendacondiçãoPgto: TStringField;
    QVendacliente: TStringField;
    QCompratransportadora: TStringField;
    QContasPagarnumnota: TIntegerField;
    QContasPagarserienota: TWideStringField;
    QContasPagarnumparcela: TIntegerField;
    QContasPagaridfornecedor: TIntegerField;
    QContasPagaridusuario: TIntegerField;
    QContasPagaridformapagamento: TIntegerField;
    QContasPagardataemissao: TDateField;
    QContasPagardatavencimento: TDateField;
    QContasPagardatapagamento: TDateField;
    QContasPagarvalor: TFloatField;
    QContasPagarmulta: TFloatField;
    QContasPagarjuros: TFloatField;
    QContasPagardesconto: TFloatField;
    QContasPagarstatus: TWideStringField;
    QContasPagardatacadastro: TDateField;
    QContasPagardataalteracao: TDateField;
    QContasPagarobservacao: TWideStringField;
    QContasPagaridcontapagar: TIntegerField;
    QContasPagaridcompra: TIntegerField;
    QContasPagarfornecedor: TStringField;
    QContasPagarformaPgto: TStringField;
    QFornecedoridfornecedor: TIntegerField;
    QFornecedornome_razaosocial: TWideStringField;
    QFornecedorlogradouro: TWideStringField;
    QFornecedornumero: TWideStringField;
    QFornecedorcep: TWideStringField;
    QFornecedorbairro: TWideStringField;
    QFornecedorcomplemento: TWideStringField;
    QFornecedoridcidade: TIntegerField;
    QFornecedoremail: TWideStringField;
    QFornecedortelefone: TWideStringField;
    QFornecedorcelular: TWideStringField;
    QFornecedorcpf_cnpj: TWideStringField;
    QFornecedortipopessoa: TWideStringField;
    QFornecedorrg_ie: TWideStringField;
    QFornecedordatanasc_fund: TDateField;
    QFornecedoridcondicaopagamento: TIntegerField;
    QFornecedordatacadastro: TDateField;
    QFornecedordataalteracao: TDateField;
    QFornecedorobservacao: TWideStringField;
    QFornecedortipofavorecido: TWideStringField;
    QFornecedorcidade: TStringField;
    QClientecidade: TStringField;
    QClientecondiçãoPgto: TStringField;
    QFornecedorcondiçãoPgto: TStringField;
    QCondicaoPagamentoformaPgto: TStringField;
    QFuncionariocargo: TStringField;
    QFuncionariocidade: TStringField;
    QUsuariofuncionário: TStringField;
    QContasPagarfuncionário: TStringField;
    QContasReceberfuncionário: TStringField;
    QComprafuncionário: TStringField;
    QVendafuncionário: TStringField;
    QUsuarioperfil: TWideStringField;
    QPaisidpais: TIntegerField;
    QPaisdescricao: TWideStringField;
    QPaisddi: TWideStringField;
    QPaisdatacadastro: TDateField;
    QPaisdataalteracao: TDateField;
    QPaissigla: TWideStringField;
    QGenerica: TZQuery;
    QTransportadora: TZQuery;
    QTransportadoraidtransportadora: TIntegerField;
    QTransportadorarazaosocial: TWideStringField;
    QTransportadoralogradouro: TWideStringField;
    QTransportadoranumero: TWideStringField;
    QTransportadoracep: TWideStringField;
    QTransportadorabairro: TWideStringField;
    QTransportadoracomplemento: TWideStringField;
    QTransportadoraidcidade: TIntegerField;
    QTransportadoraemail: TWideStringField;
    QTransportadoratelefone: TWideStringField;
    QTransportadoracelular: TWideStringField;
    QTransportadoracnpj: TWideStringField;
    QTransportadoraie: TWideStringField;
    QTransportadoradatafundacao: TDateField;
    QTransportadoraidcondicaopagamento: TIntegerField;
    QTransportadoradatacadastro: TDateField;
    QTransportadoradataalteracao: TDateField;
    QTransportadoraobservacao: TWideStringField;
    DSTransportadora: TDataSource;
    UpdateTransportadora: TZUpdateSQL;
    QProdutoidproduto: TIntegerField;
    QProdutodescricao: TWideStringField;
    QProdutoquantidade: TFloatField;
    QProdutoicms: TFloatField;
    QProdutoipi: TFloatField;
    QProdutopreco_compra: TFloatField;
    QProdutopreco_venda: TFloatField;
    QProdutoicms_anterior: TFloatField;
    QProdutoipi_anterior: TFloatField;
    QProdutopreco_compra_ant: TFloatField;
    QProdutoidmarca: TIntegerField;
    QProdutoidcategoria: TIntegerField;
    QProdutoobservacao: TWideStringField;
    QProdutodatacadastro: TDateField;
    QProdutodataalteracao: TDateField;
    QVeiculo: TZQuery;
    UpdateVeiculo: TZUpdateSQL;
    DSVeiculo: TDataSource;
    QVeiculoidveiculo: TIntegerField;
    QVeiculoantt: TWideStringField;
    QVeiculoplaca: TWideStringField;
    QVeiculouf: TWideStringField;
    QVeiculodatacadastro: TDateField;
    QVeiculodataalteracao: TDateField;
    QNcm: TZQuery;
    DSNcm: TDataSource;
    UpdateNcm: TZUpdateSQL;
    QNcmidncm: TIntegerField;
    QNcmnumero: TIntegerField;
    QNcmporcentagem_ipi: TFloatField;
    QNcmdatacadastro: TDateField;
    QNcmdataalteracao: TDateField;
    QCfop: TZQuery;
    DSCfop: TDataSource;
    UpdateCfop: TZUpdateSQL;
    QCfopidcfop: TIntegerField;
    QCfopnome: TWideStringField;
    QCfopnumero: TIntegerField;
    QCfopdatacadastro: TDateField;
    QCfopdataalteracao: TDateField;
    QProdutocst: TWideStringField;
    QProdutoidncm: TIntegerField;
    QProdutounidade: TWideStringField;
    QProdutoCompracst: TIntegerField;
    QProdutoCompraidcfop: TIntegerField;

  private
    { Private declarations }

  public
    { Public declarations }
    procedure DataModuleCreate;
    procedure beginTrans;
    procedure Commit;
    procedure rollback;
  end;

var
  DM: TDM;

implementation

{$R *.dfm}

{ TDM }

procedure TDM.beginTrans;
begin
    self.DB.StartTransaction;
end;

procedure TDM.Commit;
begin
    self.DB.Commit;
end;

procedure TDM.DataModuleCreate;
var
    ini: TIniFile;
begin
    ini := TIniFile.Create(ExtractFilePath(Application.exeName)+'config.ini');
    DB.Protocol := ini.ReadString('CONEXAO','protocolo','');
    DB.HostName := ini.ReadString('CONEXAO','hostName','');
    DB.Port := ini.ReadInteger('CONEXAO','porta',0);
    DB.Database := ini.ReadString('CONEXAO','banco','');
    DB.User := ini.ReadString('CONEXAO','usuario','');
    DB.Password := ini.ReadString('CONEXAO','senha','');
    ini.Destroy;
end;

procedure TDM.rollback;
begin
    self.DB.Rollback;
end;
end.
